### ISSUE TITLE
flutter run 后再次flutter  run 报错

### ISSUE THREAD

**Issue by JsonYuu** [hust-MC/FlutterEventMonitor#1]
如题

**Comment by JsonYuu** [comment]
log:
[+7240 ms] Start Inspector Transformer555
[   +2 ms] widget class is : Class(Widget)
[        ] user class is : null
[+2067 ms] Unhandled exception:
[        ] Crash when compiling null,
[        ] at character offset null:
[        ] NoSuchMethodError: The getter 'enclosingLibrary' was called on null.
[        ] Receiver: null
[        ] Tried calling: enclosingLibrary
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
[        ] #1      WidgetCreatorTracker._transformClassImplementingWidget (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:260:33)
[        ] #2      WidgetCreatorTracker._transformWidgetConstructors (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:406:7)
[        ] #3      WidgetCreatorTracker._transformWidgetConstructors (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:385:7)
[        ] #4      WidgetCreatorTracker._transformWidgetConstructors (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:385:7)
[        ] #5      WidgetCreatorTracker.transform (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:340:9)
[        ] #6      InspectorTransformer.transform (file:///C:/gittest/aspectd/lib/src/transformer/aop/inspector_transformer.dart:14:28)
[        ] #7      FlutterTarget.performPreConstantEvaluationTransformations (package:vm/target/flutter.dart:75:40)
[        ] #8      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1093:19)
[        ] #9      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:390:7)
[        ] <asynchronous suspension>
[        ] #10     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
[        ] #11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
[        ] #12     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
[        ] #13     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)
[        ] <asynchronous suspension>
[   +1 ms] #14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
[        ] #15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
[        ] #16     new Future.sync (dart:async/future.dart:223:31)
[        ] #17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
[        ] #18     _rootRun (dart:async/zone.dart:1190:13)
[        ] #19     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #20     _runZoned (dart:async/zone.dart:1630:10)
[        ] #21     runZoned (dart:async/zone.dart:1550:10)
[        ] #22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
[        ] #23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
[        ] #24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
[        ] #25     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)
[   +1 ms] #26     new Future.<anonymous closure> (dart:async/future.dart:175:37)
[        ] #27     _rootRun (dart:async/zone.dart:1182:47)
[        ] #28     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #29     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] #30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] #31     _rootRun (dart:async/zone.dart:1190:13)
[        ] #32     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
[        ] #34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] #35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
[        ] #36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
[        ] #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
[        ] #1      WidgetCreatorTracker._transformClassImplementingWidget (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:260:33)
[        ] #2      WidgetCreatorTracker._transformWidgetConstructors (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:406:7)
[        ] #3      WidgetCreatorTracker._transformWidgetConstructors (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:385:7)
[        ] #4      WidgetCreatorTracker._transformWidgetConstructors (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:385:7)
[        ] #5      WidgetCreatorTracker.transform (file:///C:/gittest/aspectd/lib/src/transformer/aop/track_visitor.dart:340:9)
[        ] #6      InspectorTransformer.transform (file:///C:/gittest/aspectd/lib/src/transformer/aop/inspector_transformer.dart:14:28)
[        ] #7      FlutterTarget.performPreConstantEvaluationTransformations (package:vm/target/flutter.dart:75:40)
[        ] #8      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1093:19)
[        ] #9      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:390:7)
[        ] <asynchronous suspension>
[        ] #10     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
[        ] #11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
[        ] #12     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:380:12)
[        ] #13     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:274:28)
[        ] <asynchronous suspension>
[        ] #14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
[        ] #15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
[        ] #16     new Future.sync (dart:async/future.dart:223:31)
[        ] #17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
[        ] #18     _rootRun (dart:async/zone.dart:1190:13)
[        ] #19     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #20     _runZoned (dart:async/zone.dart:1630:10)
[        ] #21     runZoned (dart:async/zone.dart:1550:10)
[        ] #22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
[        ] #23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
[        ] #24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
[        ] #25     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)
[        ] #26     new Future.<anonymous closure> (dart:async/future.dart:175:37)
[        ] #27     _rootRun (dart:async/zone.dart:1182:47)
[        ] #28     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #29     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] #30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] #31     _rootRun (dart:async/zone.dart:1190:13)
[        ] #32     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
[        ] #34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] #35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
[        ] #36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
[        ] #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[  +92 ms] the Dart compiler exited unexpectedly.
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:729:13)
           #2      _rootRun (dart:async/zone.dart:1182:47)
           #3      _CustomZone.run (dart:async/zone.dart:1093:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
           #13     _rootRun (dart:async/zone.dart:1182:47)
           #14     _CustomZone.run (dart:async/zone.dart:1093:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
           #25     _rootRun (dart:async/zone.dart:1182:47)
           #26     _CustomZone.run (dart:async/zone.dart:1093:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:664:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
           #35     _rootRunUnary (dart:async/zone.dart:1206:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:682:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:624:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
